// Code generated by ent, DO NOT EDIT.

package hashtag

const (
	// Label holds the string label denoting the hashtag type in the database.
	Label = "hashtag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHashtag holds the string denoting the hashtag field in the database.
	FieldHashtag = "hashtag"
	// EdgePosts holds the string denoting the posts edge name in mutations.
	EdgePosts = "Posts"
	// Table holds the table name of the hashtag in the database.
	Table = "hashtags"
	// PostsTable is the table that holds the Posts relation/edge. The primary key declared below.
	PostsTable = "post_hashtags"
	// PostsInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostsInverseTable = "posts"
)

// Columns holds all SQL columns for hashtag fields.
var Columns = []string{
	FieldID,
	FieldHashtag,
}

var (
	// PostsPrimaryKey and PostsColumn2 are the table columns denoting the
	// primary key for the Posts relation (M2M).
	PostsPrimaryKey = []string{"post_id", "hashtag_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
