// Code generated by ent, DO NOT EDIT.

package hashtag

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MangoSteen0903/go-blog-graphql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Hashtag applies equality check predicate on the "hashtag" field. It's identical to HashtagEQ.
func Hashtag(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHashtag), v))
	})
}

// HashtagEQ applies the EQ predicate on the "hashtag" field.
func HashtagEQ(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHashtag), v))
	})
}

// HashtagNEQ applies the NEQ predicate on the "hashtag" field.
func HashtagNEQ(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldHashtag), v))
	})
}

// HashtagIn applies the In predicate on the "hashtag" field.
func HashtagIn(vs ...string) predicate.Hashtag {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldHashtag), v...))
	})
}

// HashtagNotIn applies the NotIn predicate on the "hashtag" field.
func HashtagNotIn(vs ...string) predicate.Hashtag {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldHashtag), v...))
	})
}

// HashtagGT applies the GT predicate on the "hashtag" field.
func HashtagGT(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldHashtag), v))
	})
}

// HashtagGTE applies the GTE predicate on the "hashtag" field.
func HashtagGTE(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldHashtag), v))
	})
}

// HashtagLT applies the LT predicate on the "hashtag" field.
func HashtagLT(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldHashtag), v))
	})
}

// HashtagLTE applies the LTE predicate on the "hashtag" field.
func HashtagLTE(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldHashtag), v))
	})
}

// HashtagContains applies the Contains predicate on the "hashtag" field.
func HashtagContains(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldHashtag), v))
	})
}

// HashtagHasPrefix applies the HasPrefix predicate on the "hashtag" field.
func HashtagHasPrefix(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldHashtag), v))
	})
}

// HashtagHasSuffix applies the HasSuffix predicate on the "hashtag" field.
func HashtagHasSuffix(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldHashtag), v))
	})
}

// HashtagEqualFold applies the EqualFold predicate on the "hashtag" field.
func HashtagEqualFold(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldHashtag), v))
	})
}

// HashtagContainsFold applies the ContainsFold predicate on the "hashtag" field.
func HashtagContainsFold(v string) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldHashtag), v))
	})
}

// HasPosts applies the HasEdge predicate on the "Posts" edge.
func HasPosts() predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PostsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, PostsTable, PostsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostsWith applies the HasEdge predicate on the "Posts" edge with a given conditions (other predicates).
func HasPostsWith(preds ...predicate.Post) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PostsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, PostsTable, PostsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Hashtag) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Hashtag) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Hashtag) predicate.Hashtag {
	return predicate.Hashtag(func(s *sql.Selector) {
		p(s.Not())
	})
}
