// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/MangoSteen0903/go-blog-graphql/ent"
)

type LoginResult struct {
	Ok    bool    `json:"ok"`
	Error *string `json:"error"`
	Token *string `json:"token"`
}

type Result struct {
	Ok    bool    `json:"ok"`
	Error *string `json:"error"`
}

type UserResult struct {
	Ok    bool      `json:"ok"`
	Error *string   `json:"error"`
	User  *ent.User `json:"user"`
}
