// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HashtagsColumns holds the columns for the "hashtags" table.
	HashtagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hashtag", Type: field.TypeString, Unique: true},
	}
	// HashtagsTable holds the schema information for the "hashtags" table.
	HashtagsTable = &schema.Table{
		Name:       "hashtags",
		Columns:    HashtagsColumns,
		PrimaryKey: []*schema.Column{HashtagsColumns[0]},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "context", Type: field.TypeString, Size: 2147483647},
		{Name: "likes", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "user_posts", Type: field.TypeInt, Nullable: true},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "posts_users_Posts",
				Columns:    []*schema.Column{PostsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "upload_img", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// PostHashtagsColumns holds the columns for the "post_hashtags" table.
	PostHashtagsColumns = []*schema.Column{
		{Name: "post_id", Type: field.TypeInt},
		{Name: "hashtag_id", Type: field.TypeInt},
	}
	// PostHashtagsTable holds the schema information for the "post_hashtags" table.
	PostHashtagsTable = &schema.Table{
		Name:       "post_hashtags",
		Columns:    PostHashtagsColumns,
		PrimaryKey: []*schema.Column{PostHashtagsColumns[0], PostHashtagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_hashtags_post_id",
				Columns:    []*schema.Column{PostHashtagsColumns[0]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "post_hashtags_hashtag_id",
				Columns:    []*schema.Column{PostHashtagsColumns[1]},
				RefColumns: []*schema.Column{HashtagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HashtagsTable,
		PostsTable,
		UsersTable,
		PostHashtagsTable,
	}
)

func init() {
	PostsTable.ForeignKeys[0].RefTable = UsersTable
	PostHashtagsTable.ForeignKeys[0].RefTable = PostsTable
	PostHashtagsTable.ForeignKeys[1].RefTable = HashtagsTable
}
