// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (h *Hashtag) Posts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = h.NamedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = h.Edges.PostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = h.QueryPosts().All(ctx)
	}
	return result, err
}

func (po *Post) Hashtags(ctx context.Context) (result []*Hashtag, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = po.NamedHashtags(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = po.Edges.HashtagsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = po.QueryHashtags().All(ctx)
	}
	return result, err
}

func (po *Post) Owner(ctx context.Context) (*User, error) {
	result, err := po.Edges.OwnerOrErr()
	if IsNotLoaded(err) {
		result, err = po.QueryOwner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Posts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = u.NamedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = u.Edges.PostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = u.QueryPosts().All(ctx)
	}
	return result, err
}
