// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Hashtag is the predicate function for hashtag builders.
type Hashtag func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
